.idea/other.xml, keywords/webui/common.py, keywords/webui/dashboard.py, keywords/webui/login_page_ui.py, keywords/webui/reporting.py, test_cases/webui/dashboard/test_verify_links_in_truenas_help_card.py, test_cases/webui/dashboard/test_verify_the_report_button_on_the_memory_card.py, test_cases/webui/login/test_login_page_ui.py
Also rework assert_copyright_text_is_correct and changed 2023 to 2024
=> Adding Test_Verify_The_Report_Button_On_The_Memory_Card

pytest.ini, requirements.txt, test_cases/webui/dashboard/test_verify_a_dashboard_card_can_be_reorder.py, test_cases/webui/dashboard/test_verify_reordering_cards_remain_after_logoff.py
Also adding allure-pytest in requirements.txt and allure reporting in pytest.ini
=> TE-1343 / Adding Test_Verify_Reordering_Cards_Remain_After_Logoff

keywords/webui/apps.py, test_cases/webui/apps/conftest.py, test_cases/webui/apps/test_install_app.py, test_cases/webui/apps/test_stop_app.py
refactored test to class format
=> refactored test to class format

helper/webui.py, keywords/webui/dashboard.py, requirements.txt, test_cases/webui/dashboard/test_verify_system_information_card_copy_version_to_clipboard.py
I also added a method to get the clipboard text in WebUI.
=> TE-1342 / Adding Test_Verify_System_Information_Card_Copy_Version_To_Clipboard

keywords/webui/apps.py, keywords/webui/common.py, test_cases/webui/apps/webdav/test_edit_webdav.py
=> Install app migration

keywords/webui/apps.py, test_cases/webui/apps/wg-easy/test_edit_wg_easy_storage.py
=> added Edit WG Easy app test

test_cases/webui/apps/webdav/test_edit_webdav.py, test_cases/webui/apps/wg-easy/test_edit_wg_easy_advanced_pod.py, test_cases/webui/apps/wg-easy/test_edit_wg_easy_network.py, test_cases/webui/apps/wg-easy/test_edit_wg_easy_resources.py, test_cases/webui/apps/wg-easy/test_edit_wg_easy_storage.py
added Edit WG Easy app advanced pod test
=> added Edit WG Easy app advanced pod test

keywords/webui/common.py, keywords/webui/pool_creation_wizard.py, xpaths/common_xpaths.py, xpaths/dashboard.py, xpaths/storage.py
I also  changed method for funtion in our xpath docstring.
=> TE-1346 / Adding Pool Creation Wizard keywords.

keywords/api/post.py, keywords/webui/apps.py, keywords/webui/datasets.py, keywords/webui/navigation.py, test_cases/conftest.py, test_cases/webui/apps/test_install_app.py, test_cases/webui/apps/webdav/test_edit_webdav.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_advanced_pod.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_configuration.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_network.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_resources.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_storage.py, xpaths/__init__.py
=> fixing BETA.1 fallout

xpaths/ssh.py
=> adding xpath.ssh file

keywords/webui/common.py, keywords/webui/data_protection.py, keywords/webui/navigation.py, keywords/webui/replication.py, keywords/webui/ssh_connection.py, test_cases/webui/replicate/conftest.py, test_cases/webui/replicate/test_create_replication_task_same_box.py, test_data/replication.csv, xpaths/common_xpaths.py, xpaths/ssh.py
adding create replication test
=> Replication migration

keywords/webui/common.py, keywords/webui/local_users.py, test_cases/webui/apps/webdav/test_edit_webdav.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_advanced_pod.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_configuration.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_network.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_resources.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy_storage.py, test_cases/webui/local_users/test_edit_user_authentication_fields.py, test_data/local_users.csv
added edit authentication fields test. refactored get_element_property()
=> added edit authentication fields test. refactored get_element_property()

keywords/webui/local_users.py, test_cases/webui/local_users/test_edit_user_directory_permissions.py
added local user home directory permissions test
=> added local user home directory permissions test

keywords/webui/common.py, keywords/webui/local_users.py, test_cases/webui/local_users/conftest.py, test_cases/webui/local_users/test_built_in_users.py, test_cases/webui/local_users/test_create_new_user.py, test_cases/webui/local_users/test_delete_new_user.py, test_cases/webui/local_users/test_edit_user_authentication_fields.py, test_cases/webui/local_users/test_edit_user_directory_permissions.py, test_cases/webui/local_users/test_edit_user_identification_fields.py, test_cases/webui/local_users/test_edit_user_user_id_and_group_fields.py, test_data/builtin_users.csv
added local user builtin users test and fixed refresh local users page
=> added local user builtin users test and fixed refresh local users page

test_cases/webui/shares/smb/conftest.py, test_cases/webui/shares/smb/test_connect_to_new_smb_share.py, test_cases/webui/shares/smb/test_create_new_smb_share.py, test_cases/webui/shares/smb/test_create_new_smb_share_with_acl.py, test_cases/webui/shares/smb/test_create_new_smb_share_with_advanced_options.py, test_cases/webui/shares/smb/test_create_new_smb_share_without_acl.py, test_cases/webui/shares/smb/test_delete_new_smb_share.py, test_cases/webui/shares/smb/test_edit_smb_share.py, test_cases/webui/shares/smb/test_edit_smb_share_acl.py
=> cleaned up smb tests

keywords/api/common.py, keywords/api/delete.py, test_cases/webui/shares/nfs/test_nfs_share_disabled_share.py
=> Local groups migration

keywords/webui/local_groups.py, test_cases/webui/local_groups/test_create_new_local_group_with_duplicate_gid.py, xpaths/common_xpaths.py
added local group dup gid test case
=> added local group dup gid test case

keywords/api/post.py, keywords/webui/common.py, keywords/webui/datasets.py, keywords/webui/local_groups.py, test_cases/webui/local_groups/conftest.py, test_cases/webui/local_groups/test_add_member_to_new_group.py, test_cases/webui/local_groups/test_create_new_local_group.py, test_cases/webui/local_groups/test_create_new_local_group_with_duplicate_gid.py
added local group add member to group test case
=> TE-1352 Local groups migration

keywords/webui/local_groups.py, test_cases/webui/local_groups/test_add_member_to_new_group.py, test_cases/webui/local_groups/test_delete_member_from_new_group.py
adding delete member from new group
=> TE_1352 Local groups migration

profiles/shared.toml, test_cases/webui/datasets/test_dataset_data_protection_card_links.py
This test cases is combining 5 test cases from Katalon in one.
=> TE-1347 / Adding Test_Dataset_Data_Protection_Card_Links

profiles/shared.toml, test_cases/webui/datasets/test_access_dataset_managing_group_quotas.py, test_cases/webui/datasets/test_access_dataset_managing_user_quotas.py, test_cases/webui/datasets/test_create_dataset.py, test_cases/webui/datasets/test_dataset_access_editing_capacity_setting.py, test_cases/webui/datasets/test_dataset_data_protection_card_links.py, test_cases/webui/datasets/test_dataset_protection_navigate_add_snapshot.py, test_cases/webui/datasets/test_verify_dataset_protection_tasks_values.py
Also, I replaced preconfigure and cleanup with fixture.
=> TE-1347 / Adding Test_Dataset_Protection_Navigate_Add_Snapshot

test_cases/webui/datasets/test_create_dataset.py, test_cases/webui/datasets/test_dataset_access_editing_capacity_setting.py
=> fix dataset running issues

keywords/api/delete.py, keywords/api/put.py, keywords/webui/datasets.py, test_cases/webui/dashboard/test_verify_dashbaord_cards_visible.py, test_cases/webui/dashboard/test_verify_links_in_truenas_help_card.py, test_cases/webui/datasets/test_access_dataset_managing_group_quotas.py, test_cases/webui/datasets/test_access_dataset_managing_user_quotas.py, test_cases/webui/datasets/test_create_dataset.py, test_cases/webui/datasets/test_dataset_access_editing_capacity_setting.py, test_cases/webui/datasets/test_dataset_data_protection_card_links.py, test_cases/webui/datasets/test_dataset_default_ui.py, test_cases/webui/datasets/test_dataset_protection_navigate_add_snapshot.py, test_cases/webui/datasets/test_dataset_roles_information.py, test_cases/webui/datasets/test_verify_dataset_protection_tasks_values.py, test_cases/webui/shares/smb/test_create_new_smb_share.py, test_cases/webui/shares/smb/test_create_new_smb_share_with_acl.py, test_cases/webui/shares/smb/test_create_new_smb_share_with_advanced_options.py, test_cases/webui/shares/smb/test_create_new_smb_share_without_acl.py
Also added some pytest.mark.random_order and reworked the order of smb name and path input.
=> TE-1347 / Adding Test_Dataset_Roles_Information

keywords/webui/navigation.py, pytest.ini, test_cases/webui/datasets/test_dataset_roles.py, test_cases/webui/datasets/test_dataset_tree.py
Adding all tree test
Added test_dataset_tree_expandable, test_dataset_tree_list, test_dataset_tree_roles and test_dataset_tree_storage
=> Adding all dataset tree test

keywords/webui/local_groups.py, test_cases/webui/local_groups/test_local_groups.py, test_data/local_groups.csv
=> added edit local group test

test_cases/webui/datasets/test_navigate_datasets.py
Added test_navigate_datasets_to_add_dataset and test_navigate_datasets_to_add_zvol.
=> TE-1347 / Adding Navigate Datasets

keywords/webui/local_groups.py, pytest.ini, test_cases/webui/local_groups/test_local_groups.py, test_data/builtin_groups.csv
added built in local group test and allure marks
=> added built in local group test and allure marks

helper/webui.py, keywords/webui/certificates.py, keywords/webui/common.py, keywords/webui/pool_creation_wizard.py, test_cases/webui/storage/pool_creation_wizard/test_create_data_strip_mirror_raidzs_pool.py, xpaths/common_xpaths.py, xpaths/datasets.py, xpaths/storage.py
I moved step header in common since there is more UI that can use it.
=> TE-1358 / Adding the first wave of certificates keywords

helper/global_config.py, keywords/api/common.py, keywords/api/delete.py, keywords/webui/common.py, keywords/webui/ssh_connection.py, test_cases/webui/ssh/test_ssh_connections.py, test_data/ssh_connections.csv
=> Te 1356 ssh migration

keywords/webui/apps.py, keywords/webui/common.py
=> App refactor

keywords/webui/apps.py, keywords/webui/common.py, keywords/webui/common_shares.py, keywords/webui/datasets.py, keywords/webui/local_groups.py, keywords/webui/local_users.py, keywords/webui/login_page_ui.py, keywords/webui/replication.py, keywords/webui/smb.py
refactor .click() to COM.click_button()
=> clean up issues

keywords/api/post.py, keywords/webui/permissions.py, keywords/webui/rsync.py, test_cases/webui/shares/smb/test_create_new_smb_share_with_acl.py, test_cases/webui/shares/smb/test_edit_smb_share_acl.py
pipeline failed because bad "import". fixed smb imports
=> fixed smb imports

keywords/api/get.py, keywords/api/post.py, keywords/api/put.py, keywords/ssh/common.py, keywords/webui/datasets.py, keywords/webui/permissions.py, pytest.ini, test_cases/webui/datasets/test_access_dataset_space_management.py, test_cases/webui/datasets/test_dataset_access_editing_capacity_setting.py, test_cases/webui/datasets/test_dataset_roles.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_dataset.py, test_cases/webui/storage/pool_creation_wizard/conftest.py, test_data/datasets.csv, test_data/read_only_admin_dataset.csv
=> TE-1462 Adding test_read_only_admin_can_read_the_dataset_ui and fixed storage and Dataset issues.

keywords/webui/common.py
=> TE-1564 / Improving set_search_field

helper/cli.py, keywords/api/post.py, keywords/webui/permissions.py, keywords/webui/smb.py, test_cases/webui/shares/smb/conftest.py, test_cases/webui/shares/smb/test_guest_user_can_connect_to_new_smb_share.py
=> Te 1498 smb guest

helper/cli.py, keywords/webui/smb.py, test_cases/webui/shares/smb/test_guest_user_can_connect_to_new_smb_share.py
Added SMB Guest write/delete and denyy with read permissions tests
=> Added SMB Guest write/delete and denyy with read permissions tests

keywords/webui/local_groups.py, test_cases/webui/ldap/test_disable_ldap.py, test_cases/webui/ldap/test_setup_ldap.py, test_cases/webui/local_groups/test_local_groups.py
Removed NAS-127356 work around
=> Pipeline fixes

keywords/api/put.py, keywords/webui/datasets.py, test_cases/webui/datasets/test_dataset_data_protection.py, test_cases/webui/datasets/test_dataset_roles.py, test_cases/webui/datasets/test_dataset_tree.py
=> TE-1567 / Fixed set_app_pool, dataset_data_protection_card_links and added force to delete apps datasets

keywords/webui/navigation.py, keywords/webui/system_services.py, test_cases/webui/shares/smb/test_connect_to_new_smb_share.py
adding SMB user with Home Directory set to share
=> Te 1499 smb home dir ad

keywords/api/delete.py, keywords/api/post.py, keywords/webui/common.py, keywords/webui/datasets.py, keywords/webui/permissions.py, keywords/webui/snapshots.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_dataset.py, test_data/read_only_admin_dataset.csv, xpaths/common_xpaths.py
=> TE-1462 / Adding all test related to Read Only Admin Dataset

keywords/api/dataset.py, keywords/api/iscsi.py, keywords/webui/common.py, keywords/webui/common_shares.py, keywords/webui/iscsi.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_dataset.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_share.py, test_data/read_only_admin_shares.csv, xpaths/__init__.py, xpaths/common_xpaths.py, xpaths/sharing.py
I changed Common.is_visible to expect StaleElementReferenceException to have an exception.
=> TE-1463 / Adding read only admin iscsi tests

keywords/api/post.py, keywords/webui/smb.py, keywords/webui/snapshots.py, test_cases/webui/shares/smb/test_smb_shadow_copy.py
=> Te 1500 smb shadow copy

test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
added SMB enumeration test case
=> added SMB enumeration test case

keywords/webui/common_shares.py, test_cases/webui/shares/nfs/test_nfs_share_card_ui.py, test_cases/webui/ui/test_smb_share_ui.py, xpaths/common_xpaths.py
added SMB Share Card UI test case
=> added SMB Share Card UI test case

keywords/webui/common.py, keywords/webui/smb.py, test_cases/webui/ui/test_smb_share_acl_ui.py
added SMB Share ACL UI test case
=> added SMB Share ACL UI test case

keywords/webui/common.py, keywords/webui/common_shares.py, keywords/webui/iscsi.py, keywords/webui/nfs.py, pytest.ini, test_cases/webui/dashboard/test_dashboard_card_can_be_reorder.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_share.py, test_data/read_only_admin_shares.csv, xpaths/common_xpaths.py
Cleaned and some code
removed some unused items in python_functions of pytest.ini
=> TE-1463 / Adding all read-only admin test for NFS shares

keywords/webui/common_shares.py, keywords/webui/smb.py, test_cases/webui/ui/test_smb_share_acl_ui.py, test_cases/webui/ui/test_smb_share_ui.py
=> Dropdown UI ad user

test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
=> fixed test case order

keywords/webui/apps.py
=> increased time for delete

keywords/webui/common_shares.py, keywords/webui/iscsi.py, keywords/webui/smb.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_iscsi_share.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_nfs_share.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_smb_share.py, test_data/read_only_admin_shares.csv
I also rework some iSCSI keywords.
=> TE-1463 / Adding ROA test related to SMB card.

keywords/webui/datasets.py, profiles/shared.toml, test_cases/webui/permissions/read-only-admin/conftest.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_dataset.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_iscsi_share.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_nfs_share.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_smb_share.py, test_data/read_only_admin_dataset.csv, test_data/read_only_admin_shares.csv
There is 2 test that was removed since they become duplicates of 2 previous test.
=> TE-1596 / Refactored ROA Dataset test.

keywords/webui/dashboard.py
=> updated url

.idea/.gitignore, .idea/csv-editor.xml, helper/cli.py, keywords/webui/common.py, keywords/webui/common_replication.py, keywords/webui/data_protection.py, keywords/webui/replication.py, keywords/webui/rsync.py, keywords/webui/snapshots.py, test_cases/webui/replicate/conftest.py, test_cases/webui/replicate/test_create_replication_task_different_box.py, test_cases/webui/ssh/test_rsync_connections.py, xpaths/common_xpaths.py
=> Te 1503 replicate nas t1154

.idea/csv-editor.xml, keywords/ssh/common.py, keywords/webui/rsync.py, test_cases/webui/shares/smb/test_connect_to_new_smb_share.py, test_cases/webui/ssh/conftest.py, test_cases/webui/ssh/test_rsync_connections.py
Fixed and refactored Rsync tests
=> Pipeline fixes - SSH Rsync

.idea/csv-editor.xml, keywords/ssh/common.py, keywords/webui/rsync.py, test_cases/webui/shares/smb/test_connect_to_new_smb_share.py, test_cases/webui/ssh/conftest.py, test_cases/webui/ssh/test_rsync_connections.py
TE-1503/24.10.0/Pipeline-fixes for Rsync
=> TE-1503/24.10.0/Pipeline-fixes for Rsync

test_cases/webui/ssh/test_ssh_connections.py
fix SSH test where private SSH_USERNAME getting incorrectly updated
=> Pipeline-fixes-EE-port

test_cases/webui/ssh/conftest.py, test_cases/webui/ssh/test_rsync_connections.py
=> TE-1659/24.04.0/pipeline fix Replication

test_cases/webui/ssh/conftest.py, test_cases/webui/ssh/test_rsync_connections.py
fix incorrect logic in testcase
=> TE-1659/24.10.0/pipeline fix Replication

keywords/webui/local_users.py, test_cases/webui/local_users/test_builtin_users.py, test_cases/webui/local_users/test_local_users.py, xpaths/__init__.py, xpaths/common_xpaths.py, xpaths/local_users.py
fix pipeline test cases for changes between DF and EE
=> TE-1646/24.10.0/pipeline fix Local Users

keywords/webui/local_groups.py, test_cases/webui/local_groups/test_builtin_groups.py, test_cases/webui/local_groups/test_local_groups.py, xpaths/__init__.py, xpaths/local_groups.py, xpaths/local_users.py
fixing xpaths and missing test logic
Currently builtin tests fail due to issue NAS-128406
=> TE-1645/24.10.0/pipeline fix Local Groups

keywords/webui/replication.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy.py, test_cases/webui/replicate/test_create_replication_task_different_box.py
fix test step order for hidden udp port field
=> TE-1710/24.04.0/pipeline fix Apps WG-Easy

keywords/webui/replication.py, test_cases/webui/apps/wg_easy/test_edit_wg_easy.py, test_cases/webui/replicate/test_create_replication_task_different_box.py
fix test step order for hidden udp port field
=> TE-1710/24.10.0/pipeline fix Apps WG-Easy

test_cases/webui/shares/smb/test_delete_new_smb_share.py, test_cases/webui/ssh/test_ssh_connections.py
SSH: Added wait for right panel to close
SMB: Added Navigate to shares page to refresh shares page
=> TE-1709/24.04.0/pipeline fix SSH and SMB

test_cases/webui/shares/smb/test_delete_new_smb_share.py, test_cases/webui/ssh/test_ssh_connections.py
Added wait for right panel to close
Added Navigate to shares page to refresh shares page
=> TE-1709/24.10.0/pipeline fix SSH and SMB

keywords/webui/ssh_connection.py
Added Navigate to ssh delete keypair to refresh backup credentials page
Changed wait to wait until for better timing
=> TE-1709/24.10.0/pipeline fix SSH timing

test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
fix pipeline issues-ensure ssh service started
=> TE-1715/24.10.0/pipeline fix SMB

test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
fix pipeline issues-ensure ssh service started
=> TE-1715/24.04.0/pipeline fix SMB

keywords/api/delete.py, keywords/api/post.py, keywords/webui/common.py, keywords/webui/data_protection.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_scrub_tasks.py, xpaths/__init__.py, xpaths/data_protection.py
added read only admin scrub task tests
=> TE-1464/24.04.0/pipeline fix Read Only Admin Scrub Task

keywords/api/common.py, keywords/api/delete.py, keywords/api/get.py, keywords/api/post.py, keywords/webui/common.py, keywords/webui/data_protection.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_scrub_tasks.py, xpaths/__init__.py, xpaths/data_protection.py
added read only admin scrub task tests
=> TE-1464/24.10.0/pipeline fix Read Only Admin Scrub Task

keywords/api/delete.py, keywords/api/post.py, keywords/api/put.py, keywords/webui/common.py, keywords/webui/data_protection.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_cloud_sync_tasks.py, test_data/.gitignore, xpaths/data_protection.py
added read-only admin cloud sync task tests
=> TE-1465/24.04.0/pipeline fix Read Only Admin Cloud Sync Task

keywords/api/delete.py, keywords/api/post.py, keywords/api/put.py, keywords/webui/common.py, keywords/webui/data_protection.py, test_cases/webui/permissions/read-only-admin/test_read_only_admin_cloud_sync_tasks.py, test_data/.gitignore, xpaths/data_protection.py
added read-only admin cloud sync task tests
=> TE-1465/24.10.0/pipeline fix Read Only Admin Cloud Sync Task

test_cases/webui/permissions/read-only-admin/test_read_only_admin_cloud_sync_tasks.py, test_cases/webui/permissions/share-admin/test_share_admin_cloud_sync_tasks.py
added share admin cloud sync task tests
=> TE-1465/24.04.0/pipeline fix Share Admin Cloud Sync Task

test_cases/webui/permissions/read-only-admin/test_read_only_admin_cloud_sync_tasks.py, test_cases/webui/permissions/share-admin/test_share_admin_cloud_sync_tasks.py
added share admin cloud sync task tests
=> TE-1465/24.10.0/pipeline fix Share Admin Cloud Sync Task

keywords/api/delete.py, keywords/api/put.py, keywords/webui/data_protection.py, test_cases/webui/restricted_admin/read-only-admin/conftest.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py, xpaths/data_protection.py
add read-only admin periodic snapshot tests
=> TEN-1022/24.04.0/pipeline fix Read Only Admin Periodic Snapshot Task

keywords/api/delete.py, keywords/api/put.py, keywords/webui/data_protection.py, test_cases/webui/restricted_admin/read-only-admin/conftest.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py, xpaths/data_protection.py
add read-only admin periodic snapshot tests
=> TEN-1022/24.10.0/pipeline fix Read Only Admin Periodic Snapshot Task

test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py, xpaths/common_xpaths.py
added share admin Periodic Snapshot task tests
=> TEN-1022/24.10.0/pipeline fix Share Admin Periodic Snapshot Task

test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py, xpaths/common_xpaths.py
added share admin Periodic Snapshot task tests
=> TEN-1022/24.04.0/pipeline fix Share Admin Periodic Snapshot Task

.idea/csv-editor.xml, keywords/webui/local_groups.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_groups.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
added read-only admin Local Groups tests
=> TEN-1028/24.10.0/pipeline fix Read Only Admin Local Groups

test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_local_groups.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
added share admin Local Groups tests
=> TEN-1028/24.04.0/pipeline fix Share Admin Local Groups

test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_local_groups.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
added share admin Local Groups tests
=> TEN-1028/24.10.0/pipeline fix Share Admin Local Groups

keywords/webui/local_users.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_users.py
added read-only admin Local Users tests
=> TEN-1029/24.10.0/pipeline fix Read Only Admin Local Users

keywords/webui/local_users.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_users.py
added read-only admin Local Users tests
=> TEN-1029/24.04.0/pipeline fix Read Only Admin Local Users

test_cases/webui/restricted_admin/share-admin/test_share_admin_local_users.py
added share admin Local Users tests
=> TEN-1029/24.04.0/pipeline fix Share Admin Local Users

test_cases/webui/restricted_admin/share-admin/test_share_admin_local_users.py
added share admin Local Users tests
=> TEN-1029/24.10.0/pipeline fix Share Admin Local Users

keywords/webui/dashboard.py, test_cases/webui/dashboard/test_cpu_card_text.py, test_cases/webui/dashboard/test_dashboard_card_can_be_reorder.py, test_cases/webui/dashboard/test_dashboard_card_reordering_can_be_cancel.py, test_cases/webui/dashboard/test_default_dashboard_cards_are_visible.py, test_cases/webui/dashboard/test_disable_and_enable_dashboard_cards.py, test_cases/webui/dashboard/test_links_in_truenas_help_card.py, test_cases/webui/dashboard/test_reordering_cards_remain_after_logoff.py, test_cases/webui/dashboard/test_system_information_card_copy_version_to_clipboard.py, test_cases/webui/dashboard/test_system_information_card_ui.py, test_cases/webui/dashboard/test_system_information_card_uptime_resets_on_reboot.py, test_cases/webui/dashboard/test_the_check_for_update_button_on_the_dashboard.py, test_cases/webui/dashboard/test_the_report_button_on_the_cpu_card.py, test_cases/webui/dashboard/test_the_report_button_on_the_memory_card.py, test_cases/webui/dashboard/test_the_report_button_on_the_network_card.py, test_cases/webui/dashboard/test_the_report_button_on_the_storage_card.py, xpaths/dashboard.py
I also added some allure.issue and some todo.
=> TE-1139 / 24.10 / Fixing UI test and adding skip for missing feature

keywords/webui/common.py, keywords/webui/common_shares.py, keywords/webui/iscsi.py, keywords/webui/smb.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
refactor share admin Shares tests
=> TEN-1027/24.04.0/pipeline refactor Share Admin Shares

keywords/webui/common.py, keywords/webui/common_shares.py, keywords/webui/iscsi.py, keywords/webui/smb.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
refactor Share Admin share tests
=> TEN-1027/24.10.0/pipeline refactor Share Admin Shares

keywords/webui/smb.py, keywords/webui/system_services.py
=> TEN-1327 / 24.10 / Update SMB and SMART service xpaths

keywords/webui/data_protection.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_replication_tasks.py
added read-only admin Replication task tests
=> TEN-1024/24.04.0/pipeline add Read-Only Admin Replication task tests

.github/workflows/pylint.yml, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_general.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_general.py
added read-only admin System Settings General tests
added share admin System Settings General tests
=> TEN-1016 / 24.04.1.1 / add RO Admin - Share Admin System Settings General tests

test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
=> TEN-1352/24.04.02/shares-admin-enabled-mismatch

test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_advanced.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_advanced.py, xpaths/__init__.py, xpaths/system.py
added read-only admin System Settings Advanced tests
added share admin System Settings Advanced tests
=> TEN-1035/24.04.2/pipeline add Read-Only Admin Share Admin System Settings Advanced tests

keywords/webui/common.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_advanced.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_advanced.py
Refactor is visible to is_<obj>_visible for ease of use
=> Refactor is visible

keywords/webui/common.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_advanced.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_advanced.py
Refactor is visible ee to is_<obj>_visible for ease of use
=> Refactor is visible ee

keywords/webui/nfs.py, keywords/webui/smb.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
fixed share admin shares Page title
=> TEN-1315/24.10.0/pipeline add Share Admin Shares tests

keywords/webui/common.py
refactor is_restricted method code
the one "broken" test is related to LDAP and not the refactor
=> TEN-1363/24.10.0/refacter is restricted method code

keywords/webui/common_shares.py, keywords/webui/iscsi.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_iscsi_share.py
fixed issues with converting 'iscsi' to 'iscsitarget'
=> TEN-1370/24.04.2/pipeline add Read-Only Admin Iscsi Share tests

keywords/webui/common.py, test_cases/webui/replicate/test_create_replication_task_different_box.py
fixed infinite loop and schedule trigger if timing is off
=> TEN-1370/24.04.2/pipeline fix infinite loop on replication

helper/webui.py, keywords/webui/local_users.py, test_cases/webui/active_directory/test_active_directory.py, test_cases/webui/dashboard/test_default_dashboard_cards_are_visible.py, test_cases/webui/datasets/test_create_dataset.py, test_cases/webui/local_users/test_local_users.py, test_cases/webui/login/test_login_page_ui.py, test_cases/webui/storage/test_storage_dashboard.py
I also expended WebUI.take_percy_snapshot to support scop.
=> Adding percy in multiple test to test further Percy.

keywords/api/post.py, keywords/webui/common.py, test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_services.py
added share admin Services tests
=> TEN-1038/24.10.0/pipeline add Share Admin Services tests

.github/workflows/pylint.yml, keywords/webui/certificates.py, keywords/webui/common.py, keywords/webui/data_protection.py, test_cases/webui/datasets_permissions/nfsv4_permissions/test_create_dataset_with_nfsv4_acl.py, test_cases/webui/datasets_permissions/posix_permissions/test_posix_custom_preset.py, test_cases/webui/datasets_permissions/posix_permissions/test_posix_presets.py, test_cases/webui/datasets_permissions/posix_permissions/test_posix_recursive_permissions.py, test_cases/webui/datasets_permissions/unix_permissions/test_unix_permissions.py, test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_replication_tasks.py, test_cases/webui/shares/nfs/test_edit_nfs_share.py
W0511
- keywords-common.py:1481 -- Search field 'data-test' tag on Apps Discover page
- keywords-dashboard.py:37 -- "Thread" and "Usage" fields on CPU Graph 
- keywords-dashboard.py:458 -- Card Order needs updating
- keywords-dashboard.py:473 -- Card Order needs updating
- keywords-data_protection.py:566 -- NAS-128725
- keywords-local_groups.py:404 -- '_ssh' group
- keywords-local_groups.py:421 -- '_ssh' group
- keywords-local_groups.py:437 -- '_ssh' group
- keywords-local_groups.py:452 -- '_ssh' group
- keywords-local_groups.py:467 -- '_ssh' group
- keywords-local_groups.py:482 -- '_ssh' group
- keywords-permissions.py:658 -- refactor verify_dataset_permissions/name methods
- keywords-reporting.py:66 -- NAS-127431
- test_cases-test_dashboard_card_can_be_reorder.py:20 -- dashboard Card …
=> TEN-1429 / 24.10 / fixing pylint TODO and Allure issues

keywords/webui/replication.py, test_cases/webui/replicate/test_replication_task_encryption.py, xpaths/datasets.py
add replication encrypted to unencrypted tests.
Also retested datasets encryption because changed the "is_locked()" xpath. tests pass
=> TEN-1069/24.10.0/replication encrypted to unencrypted tests

keywords/webui/common.py, keywords/webui/replication.py, test_cases/webui/replicate/test_create_replication_task_remote_box.py
Ten 1075 replicate download logs
=> TEN-1075/24.10.0/replication download logs tests

conftest.py, test_cases/webui/dashboard/test_default_dashboard_cards_are_visible.py
comment out percy lines causing hanging
=> TEN-1435 / 24.04.2 / comment out percy lines causing hanging
